// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamFlow.API.Data;

#nullable disable

namespace TeamFlow.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamFlow.API.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskId"));

                    b.Property<string>("AssigneeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TaskId");

                    b.HasIndex("AssigneeName");

                    b.HasIndex("Status");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            AssigneeName = "Sarah Connor",
                            CreatedAt = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Status = "In Progress",
                            Title = "Design homepage wireframes & layout",
                            UpdatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TaskId = 2,
                            AssigneeName = "John Doe",
                            CreatedAt = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Status = "To Do",
                            Title = "Implement task controller REST API",
                            UpdatedAt = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TaskId = 3,
                            AssigneeName = "Alex Rivera",
                            CreatedAt = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Medium",
                            Status = "Done",
                            Title = "Create PostgreSQL database schema & migrations",
                            UpdatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TaskId = 4,
                            AssigneeName = "Emily Chen",
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Medium",
                            Status = "To Do",
                            Title = "Test Swagger API endpoints & frontend integration",
                            UpdatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TaskId = 5,
                            AssigneeName = "Michael Scott",
                            CreatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Status = "To Do",
                            Title = "Prepare SE3090 project documentation & presentation",
                            UpdatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
